# Local Development Configuration
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "0a5396ee55e709188d97bcbfffe50795"
application_url = "https://shopframe.karvocrm.store"
embedded = true
name = "shopframe"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://shopframe.karvocrm.store/auth/callback",
  "https://shopframe.karvocrm.store/auth/shopify/callback",
  "https://shopframe.karvocrm.store/auth/tokens/callback",
  "https://shopframe.karvocrm.store/billing/callback",
]

[build]
automatically_update_urls_on_dev = true

[pos]
embedded = false

[nav_menu]
  [[nav_menu.items]]
  name = "Dashboard"
  url = "/app"

  [[nav_menu.items]]
  name = "Templates"
  url = "/app/templates"

  [[nav_menu.items]]
  name = "Customize"
  url = "/app/customize"

  [[nav_menu.items]]
  name = "Pricing"
  url = "/app/pricing"

  [[nav_menu.items]]
  name = "Settings"
  url = "/app/settings"

  [[nav_menu.items]]
  name = "Support"
  url = "/app/support"
