# Local Development Configuration
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "0a5396ee55e709188d97bcbfffe50795"
application_url = "https://shopframe.karvocrm.store"
embedded = true
name = "shopframe"

[webhooks]
api_version = "2026-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/webhooks/customers/redact"
  customer_data_request_url = "/webhooks/customers/data_request"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes"

[auth]
redirect_urls = [
  "https://shopframe.karvocrm.store/auth/callback",
  "https://shopframe.karvocrm.store/auth/shopify/callback",
  "https://shopframe.karvocrm.store/auth/tokens/callback",
  "https://shopframe.karvocrm.store/billing/callback",
]

[build]
automatically_update_urls_on_dev = false

[pos]
embedded = false
